### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBase.jl#5]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
Somehow, TagBot is not working...

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register()

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by GiggleLiu** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register

**Comment by Roger-luo** [comment]
@JuliaRegistrator register
